### ISSUE TITLE
バイナリが公開されていない?

### ISSUE THREAD

**Issue by Itsuki0222** [defaultRamen/PacketSend#1]

**Comment by Itsuki0222** [comment]
できればコンパイル済みバイナリを公開してください

**Comment by defaultRamen** [comment]
公開しました

**Comment by Itsuki0222** [comment]
今度はソースコードが消えていますが...

**Comment by defaultRamen** [comment]
ソースコードいるのか
まかせとけ

2024年7月17日(水) 16:59 Itsuki0222 ***@***.***>:

**Comment by defaultRamen** [comment]
StdOutクラスとMainクラスは別に別々に分ける必要ないからSend.javaに統合したで

2024年7月17日(水) 17:05 びw ***@***.***>:

**Comment by Itsuki0222** [comment]
たいていどっちも公開されている気がしたので

**Comment by Itsuki0222** [comment]
じゃあなぜ分けていた...

**Comment by defaultRamen** [comment]
気分

**Comment by Itsuki0222** [comment]
？？？

**Comment by defaultRamen** [comment]
final class とかは最近覚えた
インスタンス化もなんか面白いから使ってた

**Comment by Itsuki0222** [comment]
これ普通に公開するプログラムだったら無駄の無い内容にしなければ...

**Comment by Itsuki0222** [comment]
てか公開してるけど

**Comment by defaultRamen** [comment]
そんな仕事みたいなものでもないですしお寿司

**Comment by defaultRamen** [comment]
そんなに最適化？はしなくてもいい

**Comment by Itsuki0222** [comment]
まあ多分僕のプログラムも無駄多いと思う
